apiVersion: v1
kind: ServiceAccount
metadata:
  name: locaguide-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locaguide-worker
automountServiceAccountToken: false
