apiVersion: v1
kind: ServiceAccount
metadata:
  name: locaguide-api
  namespace: locaguide
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locaguide-worker
  namespace: locaguide
automountServiceAccountToken: false
