import type { Evidence } from "@locaguide/contracts";
import { RecommendationEngine } from "@locaguide/domain";
import { prisma } from "@locaguide/db";
import { buildProviderRegistry } from "./registry";
import { getEntityById } from "./entityService";
import { listOpinionsForEntity } from "./communityService";
import { getBestAvailableAspectSignals } from "./reviewService";

const engine = new RecommendationEngine();

/**
 * Generates a full evidence-based briefing for one entity (section 43) and
 * persists it. Every item generated by RecommendationEngine already carries
 * its own evidence trail (section 8) - this function only adds storage.
 */
export async function generateBriefing(entityId: string, userId?: string): Promise<Evidence[]> {
  const { aiRouter, productProvider, dealProvider } = buildProviderRegistry();

  const [entity, aspectSignals, opinions, products] = await Promise.all([
    getEntityById(entityId),
    getBestAvailableAspectSignals(entityId),
    listOpinionsForEntity(entityId, 1, 20),
    productProvider.getProductsForEntity(entityId),
  ]);
  const deals = (await Promise.all(products.map((p) => dealProvider.getActiveDealsForProduct(p.id)))).flat();

  const evidence = await engine.generate({
    entity,
    aspectSignals,
    communityOpinions: opinions.items,
    products,
    deals,
    aiProvider: aiRouter,
    now: new Date(),
  });

  const recommendation = await prisma.recommendation.create({
    data: { entityId, userId: userId ?? null },
  });

  await prisma.$transaction(
    evidence.map((e) =>
      prisma.evidence.create({
        data: {
          id: e.id,
          recommendationId: recommendation.id,
          entityId: e.entityId,
          category: e.category,
          recommendation: e.recommendation,
          type: e.type,
          reason: e.reason,
          sources: e.sources,
          confidence: e.confidence,
          generatedAt: new Date(e.generatedAt),
          expiresAt: e.expiresAt ? new Date(e.expiresAt) : null,
          modelVersion: e.modelVersion,
          promptTemplateVersion: e.promptTemplateVersion,
        },
      }),
    ),
  );

  return evidence;
}
