import type { LocationEntity } from "@locaguide/contracts";

/**
 * Realistic demo/mock data so the entire product can be evaluated without any
 * paid API credentials. Clearly flagged with isDemoData: true so the client
 * can label it as demo data in the UI (see section 39 of the product spec).
 */
export const DEMO_ENTITIES: LocationEntity[] = [
  {
    id: "demo-mall-1",
    tenantId: null,
    name: "Riverside Central Mall",
    category: "SHOPPING_MALL",
    secondaryCategories: ["FOOD_COURT", "CINEMA"],
    address: "12 Riverside Ave, Springfield",
    location: { latitude: 17.4239, longitude: 78.4738 },
    rating: 4.2,
    reviewCount: 3120,
    openingHours: [
      { dayOfWeek: 0, opens: "10:00", closes: "22:00", closedAllDay: false },
      { dayOfWeek: 1, opens: "10:00", closes: "22:00", closedAllDay: false },
      { dayOfWeek: 2, opens: "10:00", closes: "22:00", closedAllDay: false },
      { dayOfWeek: 3, opens: "10:00", closes: "22:00", closedAllDay: false },
      { dayOfWeek: 4, opens: "10:00", closes: "22:00", closedAllDay: false },
      { dayOfWeek: 5, opens: "10:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 6, opens: "10:00", closes: "23:00", closedAllDay: false },
    ],
    website: "https://example.com/riverside-central-mall",
    phone: "+91-40-0000-0001",
    accessibility: ["wheelchair_accessible_entrance", "wheelchair_accessible_parking"],
    sourceProvider: "mock",
    sourceProviderId: "demo-mall-1",
    attribution: "Demo data - LocaGuide Mock Location Provider",
    isDemoData: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "demo-restaurant-1",
    tenantId: null,
    name: "Spice Junction Family Restaurant",
    category: "RESTAURANT",
    secondaryCategories: ["INDIAN", "VEGETARIAN_FRIENDLY"],
    address: "45 Market Street, Springfield",
    location: { latitude: 17.425, longitude: 78.475 },
    rating: 4.5,
    reviewCount: 890,
    openingHours: [
      { dayOfWeek: 0, opens: "11:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 1, opens: "11:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 2, opens: "11:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 3, opens: "11:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 4, opens: "11:00", closes: "23:00", closedAllDay: false },
      { dayOfWeek: 5, opens: "11:00", closes: "23:30", closedAllDay: false },
      { dayOfWeek: 6, opens: "11:00", closes: "23:30", closedAllDay: false },
    ],
    website: "https://example.com/spice-junction",
    phone: "+91-40-0000-0002",
    accessibility: ["wheelchair_accessible_seating"],
    sourceProvider: "mock",
    sourceProviderId: "demo-restaurant-1",
    attribution: "Demo data - LocaGuide Mock Location Provider",
    isDemoData: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "demo-hospital-1",
    tenantId: null,
    name: "Springfield General Hospital",
    category: "HOSPITAL",
    secondaryCategories: ["EMERGENCY_CARE"],
    address: "1 Health Parkway, Springfield",
    location: { latitude: 17.4205, longitude: 78.472 },
    rating: 4.0,
    reviewCount: 2210,
    openingHours: [
      { dayOfWeek: 0, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 1, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 2, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 3, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 4, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 5, opens: "00:00", closes: "23:59", closedAllDay: false },
      { dayOfWeek: 6, opens: "00:00", closes: "23:59", closedAllDay: false },
    ],
    website: "https://example.com/springfield-general",
    phone: "+91-40-0000-0003",
    accessibility: ["wheelchair_accessible_entrance", "wheelchair_accessible_restroom"],
    sourceProvider: "mock",
    sourceProviderId: "demo-hospital-1",
    attribution: "Demo data - LocaGuide Mock Location Provider",
    isDemoData: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "demo-hotel-1",
    tenantId: null,
    name: "Grand Springfield Hotel",
    category: "HOTEL",
    secondaryCategories: ["BUSINESS", "FAMILY_FRIENDLY"],
    address: "78 Central Boulevard, Springfield",
    location: { latitude: 17.427, longitude: 78.477 },
    rating: 4.3,
    reviewCount: 1560,
    openingHours: [],
    website: "https://example.com/grand-springfield",
    phone: "+91-40-0000-0004",
    accessibility: ["wheelchair_accessible_entrance", "elevator"],
    sourceProvider: "mock",
    sourceProviderId: "demo-hotel-1",
    attribution: "Demo data - LocaGuide Mock Location Provider",
    isDemoData: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "demo-attraction-1",
    tenantId: null,
    name: "Springfield Heritage Fort",
    category: "TOURIST_ATTRACTION",
    secondaryCategories: ["HISTORICAL", "OUTDOOR"],
    address: "Fort Hill Road, Springfield",
    location: { latitude: 17.43, longitude: 78.47 },
    rating: 4.6,
    reviewCount: 5400,
    openingHours: [
      { dayOfWeek: 0, opens: "09:00", closes: "18:00", closedAllDay: false },
      { dayOfWeek: 1, opens: null, closes: null, closedAllDay: true },
      { dayOfWeek: 2, opens: "09:00", closes: "18:00", closedAllDay: false },
      { dayOfWeek: 3, opens: "09:00", closes: "18:00", closedAllDay: false },
      { dayOfWeek: 4, opens: "09:00", closes: "18:00", closedAllDay: false },
      { dayOfWeek: 5, opens: "09:00", closes: "18:00", closedAllDay: false },
      { dayOfWeek: 6, opens: "09:00", closes: "19:00", closedAllDay: false },
    ],
    website: "https://example.com/heritage-fort",
    phone: null,
    accessibility: ["limited_wheelchair_access"],
    sourceProvider: "mock",
    sourceProviderId: "demo-attraction-1",
    attribution: "Demo data - LocaGuide Mock Location Provider",
    isDemoData: true,
    fetchedAt: new Date().toISOString(),
  },
];
